#!/usr/bin/env python3
# Genera la documentazione delle rotte API (docs/API.md italiano, docs/API.en.md inglese) dal CODICE (rotte, livello, parametri letti,
# codici di errore usati) + tools/api_notes.txt (descrizione). Cosi documento e codice non possono divergere.
# Uso:  python3 tools/mkapidoc.py           (scrive i due file)
#       python3 tools/mkapidoc.py --check   (errore se i file non sono allineati al codice, o se manca una descrizione)
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE); SRC = os.path.join(ROOT, 'VesevOS')
LV = {'L_PUB': 'pubblico', 'L_GUEST': 'ospite', 'L_OPER': 'operatore', 'L_ADMIN': 'admin'}
LVE = {'pubblico': 'public', 'ospite': 'guest', 'operatore': 'operator', 'admin': 'admin'}
RX = re.compile(r'add\(\s*\w+\s*,\s*\w+\s*,\s*"(/[^"]*)"\s*,\s*HTTP_(\w+)\s*,\s*(L_\w+)')

def balanced(t, i):
    d = 0
    for j in range(i, len(t)):
        if t[j] == '(': d += 1
        elif t[j] == ')':
            d -= 1
            if d == 0: return t[i:j + 1]
    return t[i:]

def args(a):
    d = 0; parts = []; cur = ''
    for ch in a[1:-1]:
        if ch in '([{': d += 1
        if ch in ')]}': d -= 1
        if ch == ',' and d == 0: parts.append(cur); cur = ''
        else: cur += ch
    parts.append(cur); return parts

def scan():
    out = {}
    for root, _, fs in os.walk(SRC):
        for f in sorted(fs):
            if not f.endswith('.cpp'): continue
            t = open(os.path.join(root, f), encoding='utf-8', errors='replace').read()
            ms = list(re.finditer(r'add\(\s*\w+\s*,\s*\w+\s*,\s*"/', t))
            for k, m in enumerate(ms):
                body = t[m.start(): ms[k + 1].start() if k + 1 < len(ms) else len(t)]
                mm = RX.match(body)
                if not mm: continue
                params = sorted(set(re.findall(r'\b(?:P|has|qparam)\(\s*r\s*,\s*"(\w+)"', body)))
                codes = set()
                for km in re.finditer(r'\bko\(', body):
                    p = args(balanced(body, km.end() - 1))
                    codes.add(p[-1].strip().strip('"') if len(p) >= 3 and p[-1].strip().startswith('"') else 'error')
                out[(mm.group(2), mm.group(1))] = (LV[mm.group(3)], params, sorted(codes))
    return out

def notes():
    d = {}
    for l in open(os.path.join(HERE, 'api_notes.txt'), encoding='utf-8'):
        if l.startswith('#') or '|' not in l: continue
        k, it, en = [x.strip() for x in l.split('|', 2)]
        d[k] = (it, en)
    return d

def build(lang):
    R = scan(); N = notes(); miss = [f'{m} {p}' for (m, p) in R if f'{m} {p}' not in N]
    it = lang == 'it'
    L = []
    w = L.append
    if it:
        w('# API di VesevOS (generato da `tools/mkapidoc.py`: non modificare a mano)\n')
        w('Versione API: **%s** (campo `apiVersion` in `/api/status` e `/api/common`). Cambia solo per rotture; aggiungere campi e sempre permesso.\n' % apiv())
        w('## Regole generali\n')
        w('- **Accesso:** cookie di sessione dopo `POST /api/login`. Livelli: `pubblico` (nessuna sessione), `ospite`, `operatore`, `admin` (ogni livello include i precedenti). Senza sessione: 401 `unauthorized`; ruolo insufficiente: 403 `forbidden`.')
        w('- **Risposta:** JSON. In errore sempre `{"ok":false,"err":"testo tradotto","code":"nome"}`; `code` e stabile (usalo nelle app), `err` cambia con la lingua.')
        w('- **Codici di errore** (il codice HTTP segue `code`):\n')
        w('| code | HTTP | quando |\n|---|---|---|\n| `error` | 400 | dato mancante o non valido (nessun cambiamento fatto) |\n| `bad_login` | 403 | nome, password o codice errati |\n| `forbidden` | 403 | ruolo insufficiente o azione non permessa |\n| `https_only` | 403 | dalla rete di casa serve HTTPS |\n| `notfound` | 404 | elemento non trovato |\n| `state` | 409 | stato non adatto (es. spegnere l\'hotspot senza Wi-Fi di casa) |\n| `toobig` | 413 | dato troppo grande |\n| `blocked` | 429 | troppi errori: IP bloccato |\n| `off` | 503 | servizio spento o pacchetto assente |\n| `unauthorized` | 401 | manca la sessione (solo questo caso usa 401) |\n')
        w('- **Limiti:** corpo massimo 48 KB; elenco file 200 voci, ricerca reti 40 reti (oltre: `more:true`). Date in secondi Unix (UTC), durate in secondi, dimensioni in byte.')
        w('- **Parametri:** `application/x-www-form-urlencoded`. Regola API 12: un valore non valido non deve cambiare nulla.')
        w('- La colonna **Parametri** e la **Errori** sono lette dal codice (indicative: gli errori elencati sono quelli esplicitamente dati dalla rotta, oltre a quelli generali sopra).\n')
        w('## Rotte (%d)\n' % len(R))
        w('| Metodo | Percorso | Livello | Cosa fa | Parametri | Errori |\n|---|---|---|---|---|---|')
    else:
        w('# VesevOS API (generated by `tools/mkapidoc.py`: do not edit by hand)\n')
        w('API version: **%s** (`apiVersion` field in `/api/status` and `/api/common`). It changes only for breaking changes; adding fields is always allowed.\n' % apiv())
        w('## General rules\n')
        w('- **Access:** session cookie after `POST /api/login`. Levels: `public` (no session), `guest`, `operator`, `admin` (each includes the previous). No session: 401 `unauthorized`; role too low: 403 `forbidden`.')
        w('- **Response:** JSON. On error always `{"ok":false,"err":"translated text","code":"name"}`; `code` is stable (use it in apps), `err` changes with the language.')
        w('- **Error codes** (the HTTP status follows `code`):\n')
        w('| code | HTTP | when |\n|---|---|---|\n| `error` | 400 | missing or invalid data (nothing changed) |\n| `bad_login` | 403 | wrong name, password or code |\n| `forbidden` | 403 | role too low or action not allowed |\n| `https_only` | 403 | from the home network HTTPS is required |\n| `notfound` | 404 | item not found |\n| `state` | 409 | unsuitable state (e.g. turning the hotspot off without home Wi-Fi) |\n| `toobig` | 413 | data too large |\n| `blocked` | 429 | too many errors: IP blocked |\n| `off` | 503 | service off or package missing |\n| `unauthorized` | 401 | no session (the only case that uses 401) |\n')
        w('- **Limits:** body up to 48 KB; file list 200 items, network scan 40 networks (beyond: `more:true`). Dates in Unix seconds (UTC), durations in seconds, sizes in bytes.')
        w('- **Parameters:** `application/x-www-form-urlencoded`. API rule 12: an invalid value must change nothing.')
        w('- The **Parameters** and **Errors** columns are read from the code (indicative: the errors listed are those the route gives explicitly, besides the general ones above).\n')
        w('## Routes (%d)\n' % len(R))
        w('| Method | Path | Level | What it does | Parameters | Errors |\n|---|---|---|---|---|---|')
    for (m, p) in sorted(R, key=lambda x: (x[1], x[0])):
        lv, params, codes = R[(m, p)]
        d = N.get(f'{m} {p}', ('?', '?'))[0 if it else 1]
        w('| %s | `%s` | %s | %s | %s | %s |' % (m, p, lv if it else LVE[lv], d.replace('|', '/'), ', '.join('`%s`' % x for x in params) or '-', ', '.join('`%s`' % x for x in codes) or '-'))
    w('')
    return '\n'.join(L), miss

def apiv():
    return re.search(r'#define\s+VOS_API_VERSION\s+(\d+)', open(os.path.join(SRC, 'src', 'core', 'vos_common.h')).read()).group(1)

if __name__ == '__main__':
    bad = 0
    for lang, fn in (('it', 'API.md'), ('en', 'API.en.md')):
        text, miss = build(lang)
        path = os.path.join(ROOT, 'docs', fn)
        if miss and lang == 'it':
            print('MANCA la descrizione in tools/api_notes.txt per:', *miss, sep='\n  '); bad = 1
        if '--check' in sys.argv:
            cur = open(path, encoding='utf-8').read() if os.path.exists(path) else ''
            if cur != text: print('docs/%s NON allineato al codice: lancia tools/mkapidoc.py' % fn); bad = 1
        else:
            open(path, 'w', encoding='utf-8', newline='\n').write(text); print('scritto docs/%s' % fn)
    if '--check' in sys.argv and not bad: print('ok: documentazione API allineata al codice')
    sys.exit(bad)
